export const ENROLL_IN_COURSE = "ENROLL_IN_COURSE";

export const COURSES_LOADING = "COURSES_LOADING";
export const COURSES_LOADING_SUCCESS = "COURSES_LOADING_SUCCESS";
export const COURSES_LOADING_FAILURE = "COURSES_LOADING_FAILURE";

export const ADDING_COURSE = "ADDING_COURSE";
